version: "2.4"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: e2etest
      POSTGRES_DB: sea_e2e
  redis:
    image: redis:5
  sea:
    image: rinsuki/sea
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: e2e
      DATABASE_URL: "postgres://postgres:e2etest@postgres/sea_e2e"
      REDIS_URL: "redis://redis"
      S3_BUCKET: todo
      S3_ENDPOINT: https://todo.invalid/
      S3_PUBLIC_URL: https://todo.invalid/
      S3_FORCE_USE_PATH_STYLE: "yes"
      SW_KEY_PUBLIC: BCcz_Cu-dyytQQKkAe4VHpcENY77MPTRU7JHv_v8M6DVGIxiw8Dw_zOk_hAMCo7gfZhcnlbM9dmZMx8oYigzXbo
      SW_KEY_PRIVATE: z5xqBapw-DYJNngSabsn80N4r-iDRHHgYeNwDnZsgKE
      SW_SUBJECT: https://rinsuki.net/only-for-e2e-test/
    links:
      - postgres
      - redis
